name: dexumi_teleop
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - cryptography>=44.0
      - numpy
      - opencv-python
      - pyserial
      - python-can
      - pyrealsense2
